server-port=25565
gamemode=creative
difficulty=peaceful
pvp=true
view-distance=20
simulation-distance=10
max-players=10
online-mode=true
motd=§aBuild Server §7| §bEn ligne
max-tick-time=-1
sync-chunk-writes=false
network-compression-threshold=256
entity-broadcast-range-percentage=100
player-idle-timeout=0
spawn-protection=0
allow-flight=true
enable-command-block=true
