# ══════════════════════════════════════════════════════
#  server.properties — Build Server optimisé
# ══════════════════════════════════════════════════════

# Réseau
server-port=25565
online-mode=true
network-compression-threshold=256
max-tick-time=-1

# Monde
level-name=world
level-type=minecraft:flat
generate-structures=false
allow-nether=true
max-world-size=29999984

# Performance
view-distance=20
simulation-distance=6
max-players=20
player-idle-timeout=0

# Build server
gamemode=creative
difficulty=peaceful
pvp=false
allow-flight=true
spawn-protection=0
spawn-monsters=false
spawn-animals=false
spawn-npcs=false

# Optimisation
sync-chunk-writes=false
use-native-transport=true
