# ══════════════════════════════════════════════════════
#  server.properties — Build Server optimisé
# ══════════════════════════════════════════════════════

# Réseau
server-port=25565
online-mode=true
network-compression-threshold=256
max-tick-time=-1
motd=\u00a78\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac \u00a7b\u00a7l\u2606 Build Server \u2606 \u00a78\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\n\u00a77\u2623 Creative \u00a78\u2502 \u00a77FAWE \u00a78\u2502 \u00a77EzEdits \u00a78\u2502 \u00a77Axiom

# Monde
level-name=world
level-type=minecraft:flat
generate-structures=false
allow-nether=true
max-world-size=29999984

# Performance
view-distance=20
simulation-distance=6
max-players=20
player-idle-timeout=0

# Build server
gamemode=creative
difficulty=peaceful
pvp=false
allow-flight=true
spawn-protection=0
spawn-monsters=false
spawn-animals=false
spawn-npcs=false

# Optimisation
sync-chunk-writes=false
use-native-transport=true
