# ══════════════════════════════════════════════════════
#  paper-world-defaults.yml — Build server optimisé
# ══════════════════════════════════════════════════════

_version: 29

anticheat:
  anti-xray:
    enabled: false
  obfuscation:
    items:
      hide-itemmeta: false
      hide-itemmeta-with-visual-effects: false

chunks:
  auto-save-interval: 6000
  delay-chunk-unloads-by: 10s
  entity-per-chunk-save-limit:
    arrow: -1
    ender_pearl: -1
    experience_orb: -1
    fireball: -1
    small_fireball: -1
    snowball: -1
  fixed-chunk-inhabited-time: -1
  max-auto-save-chunks-per-tick: 24
  prevent-moving-into-unloaded-chunks: false

collisions:
  allow-player-cramming-damage: false
  allow-vehicle-collisions: true
  fix-climbing-bypassing-cramming-rule: false
  max-entity-collisions: 2
  only-players-collide: false

entities:
  behavior:
    baby-zombie-movement-modifier: 0.5
    disable-chest-cat-detection: true
    disable-creeper-lingering-effect: false
    disable-player-crits: false
    door-breaking-difficulty:
      husk: []
      vindicator: []
      zombie: []
      zombie_villager: []
      zombified_piglin: []
    experience-merge-max-value: -1
    mobs-can-always-pick-up-loot:
      skeletons: false
      zombies: false
    nerf-pigmen-from-nether-portals: false
    parrot-natural-death: false
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    piglins-guard-chests: true
    pillager-patrols:
      disable: true
      spawn-chance: 0.0
      spawn-delay:
        per-player: false
        ticks: 12000
      start:
        day: 5
        per-player: false
    player-insomnia-start-ticks: 72000
    should-remove-dragon: false
    spawner-nerfed-mobs-should-jump: false
    zombie-villager-infection-chance: -1.0
    zombies-target-turtle-eggs: true
  despawn-ranges:
    ambient:
      hard: 128
      soft: 32
    axolotls:
      hard: 128
      soft: 32
    creature:
      hard: 128
      soft: 32
    misc:
      hard: 128
      soft: 32
    monster:
      hard: 128
      soft: 32
    underground_water_creature:
      hard: 128
      soft: 32
    water_ambient:
      hard: 64
      soft: 32
    water_creature:
      hard: 128
      soft: 32
  entities-target-with-follow-range: false
  mob-effects:
    immune-to-slow-falling: []
    immune-to-speed-change: []
  spawning:
    all-chunks-are-slime-chunks: false
    alt-item-despawn-rate:
      enabled: false
      items: {}
    count-all-mobs-for-spawning: false
    creative-arrow-despawn-rate: default
    despawn-ranges: {}
    disable-mob-spawner-spawn-egg-transformation: false
    duplicate-uuid:
      mode: SAFE_REGEN
      safe-regen-delete-range: 32
    filter-nbt-data-from-spawn-eggs-and-related: true
    iron-golems-can-spawn-in-air: false
    monster-spawn-max-light-level: -1
    non-player-arrow-despawn-rate: default
    per-player-mob-spawns: true
    scan-for-legacy-ender-dragon: true
    skeleton-horse-thunder-spawn-chance: 0.01
    slime-spawn-height:
      slime-chunk:
        maximum: 40
      surface-biome:
        maximum: 70
        minimum: 50
    spawn-limits:
      ambient: 0
      axolotls: 0
      creature: 0
      monster: 0
      underground_water_creature: 0
      water_ambient: 0
      water_creature: 0
    wandering-trader:
      spawn-chance-failure-increment: 0
      spawn-chance-max: 0
      spawn-chance-min: 0
      spawn-day-length: 24000
      spawn-minute-length: 1200
    wateranimal-spawn-height:
      maximum: default
      minimum: default

environment:
  disable-explosion-knockback: false
  disable-ice-and-snow: false
  disable-teleportation-suffocation-check: false
  disable-thunder: true
  fire-tick-delay: 30
  frosted-ice:
    delay:
      max: 40
      min: 20
    enabled: false
  generate-flat-bedrock: false
  nether-ceiling-void-damage-height: disabled
  optimize-explosions: true
  portal-create-radius: 16
  portal-search-radius: 128
  portal-search-vanilla-dimension-scaling: true
  treasure-maps:
    enabled: false
    find-already-discovered:
      loot-tables: default
      villager-trade: true
  water-over-lava-flow-speed: 5

feature-seeds:
  generate-random-seeds-for-all: false

fishing-time-range:
  maximum: 600
  minimum: 100

fixes:
  disable-unloaded-chunk-enderpearl-exploit: true
  falling-block-height-nerf: disabled
  fix-caches-on-explosions: false
  fix-items-merging-through-walls: false
  prevent-tnt-from-moving-in-water: false
  split-overstacked-loot: true
  tnt-entity-height-nerf: disabled

game-mechanics:
  arrow-infinite-fix: false
  bed-search-radius: 1
  disable-chest-cat-detection: false
  disable-end-credits: true
  disable-grindstone-gambling: false
  disable-ice-and-snow: false
  disable-instant-teleport-with-portal: false
  disable-pillager-patrols: true
  disable-player-crits: false
  disable-relative-projectile-velocity: false
  disable-sprint-interruption-on-attack: false
  disable-unloaded-chunk-enderpearl-exploit: true
  disable-wither-target-id-range: false
  exp-merge-max-value: -1
  fix-cactus-growth-ticking: false
  fix-void-trading-exploit: false
  nerf-pigmen-from-nether-portals: false
  shield-blocking-delay: 0
  show-full-armor-durability: false
  sleep-skips-if-possible-percentage: 100
  snap-to-grid: false
  use-better-mending: false

hopper:
  cooldown-when-full: true
  disable-move-event: true
  ignore-occluding-blocks: true

lootables:
  auto-replenish: false
  max-refills: -1
  refresh-max: 2d
  refresh-min: 12h
  reset-seed-on-fill: true
  restrict-player-reloot: true

maps:
  item-frame-cursor-limit: 128
  item-frame-cursor-update-interval: 10

max-growth-height:
  bamboo:
    max: 16
    min: 11
  cactus: 3
  reeds: 3

misc:
  disable-end-credits: true
  light-queue-size: 20
  max-leash-distance: 10.0
  redstone-implementation: ALTERNATE_CURRENT
  shield-blocking-delay: 0
  show-full-armor-durability: false
  update-pathfinding-on-block-update: false

scoreboards:
  allow-non-player-entities-on-scoreboards: false
  use-vanilla-world-scoreboard-name-coloring: false

spawn:
  allow-using-signs-inside-spawn-protection: false
  keep-spawn-loaded: false
  keep-spawn-loaded-range: 0

tick-rates:
  behavior:
    villager:
      validatenearbypoi: -1
      acquirepoi: -1
  container-update: 1
  grass-spread: 4
  mob-spawner: 1
  sensor:
    villager:
      secondarypoisensor: 40
      nearestbedsensor: 20
      villagerbabiessensor: 40
      playersensor: 40
      nearestlivingentitysensor: 40

unsupported-settings:
  fix-invulnerable-end-crystal-exploit: true
  perform-username-validation: true
