# ══════════════════════════════════════════════════════
#  paper-global.yml — Optimisations maximales
# ══════════════════════════════════════════════════════

_version: 29

async-chunks:
  enabled: true
  threads: -1

chunk-loading-basic:
  autoconfig-send-distance: true
  player-max-concurrent-loads: 20
  target-player-chunk-send-rate: 100.0

chunk-loading-advanced:
  auto-config-send-distance: true
  player-max-send-velocity: 18.0

chunk-system:
  gen-parallelism: default
  io-threads: -1
  worker-threads: -1

item-validation:
  display-name: 8192
  lore-line: 8192
  resolve-selectors-in-books: false

misc:
  fix-entity-position-desync: true
  load-permissions-yml-before-plugins: true
  max-joins-per-tick: 10
  region-file-cache-size: 512
  use-alternative-luck-formula: false
  chat-threads:
    chat-executor-core-size: -1
    chat-executor-max-size: -1

packet-limiter:
  all-packets:
    action: DROP
    interval: 7.0
    max-packet-rate: 500.0
  kick-message: '<red>Disconnected'
  overrides:
    ServerboundPlaceRecipePacket:
      action: DROP
      interval: 4.0
      max-packet-rate: 5.0

scoreboards:
  save-empty-scoreboard-teams: false
  track-plugin-scoreboards: false

spam-limiter:
  incoming-packet-threshold: 300
  recipe-spam-increment: 0
  tab-spam-increment: 0
  tab-spam-limit: 500

timings:
  enabled: false
  really-enabled: false
  server-name: Build Server
  url: https://timings.aikar.co
  verbose: false

watchdog:
  early-warning-delay: 10000
  early-warning-every: 5000

player-auto-save:
  max-per-tick: 20
  rate: 6000

console:
  enable-brigadier-completions: true
  enable-brigadier-highlighting: true
  has-all-permissions: false

logging:
  deobfuscate-stacktraces: true
  log-player-ip-addresses: false
